server:
  port: ${CUSTOM.SERVER.PORT:9010}

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}
    fetchRegistry: true
    healthcheck:
      enable: true
    refresh:
      enable: true

### Audit database configuration
#
spring:
  datasource:
    url: ${SERVER.DATABASE.PG.AUDIT:jdbc:postgresql://localhost:5432/audit}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
      '[format_sql]': true

# Kafka Configuration
#
kafka:
  soluya:
    topic: soluya
    server: 127.0.0.1
    port: 9092