server:
  port: ${CUSTOM.SERVER.PORT:9010}

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}
    fetchRegistry: true
    healthcheck:
      enable: true
    refresh:
      enable: true

### Mongo database configuration
#
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mitocode
      uri: mongodb://mitocode:mitocode@localhost:27017
      authentication-database: admin

# Kafka Configuration
#
kafka:
  soluya:
    topic: soluya
    server: 127.0.0.1
    port: 9092