server:
  port: ${CUSTOM.SERVER.PORT:9090}
  
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}
    fetchRegistry: true
    
spring:
  cloud:
    gateway:
      routes:
        - id: laundry-integration-nigisus
          uri: laundry-integration-nigisus
          predicates:
            - Path=/api/laundry-integration-nigisu/**
          filters:
            - StripPrefix=2