server:
  port: ${CUSTOM.SERVER.PORT:9004}
  
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}
    fetchRegistry: true

spring:
  datasource:
    url: jdbc:sybase:Tds:localhost:2638?ServiceName=faccsystem
    username: dba
    password: +formula*1234+
    driver-class-name: com.sybase.jdbc4.jdbc.SybDriver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: update
