server:
  port: ${CUSTOM.SERVER.PORT:9004}
  
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}
      
# conexion a la bdd Spring Datasource Configuration jconn4
#
spring:
  datasource:
    url: jdbc:sybase:Tds:localhost:2638/faccsystem
    username: n.tello
    password: myfriends
    driverClassName: com.sybase.jdbc4.jdbc.SybDriver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    properties:
      hibernate:
        default_schema: SCHEMA
        connection:
          useUnicode: true
          characterEncoding: UTF-8
    hibernate: ddl-auto=none
    databasePlatform: org.hibernate.dialect.SybaseASE157Dialect
    show-sql: true